CREATE TABLE IF NOT EXISTS Users(
  userId INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(1000) NOT NULL,
  state VARCHAR(1000),
  listenHistory VARCHAR(1000)
);
